name: Build firmware

on:
  push:
    branches:
      - "**"
  pull_request:
  workflow_dispatch:

permissions:
  contents: write
  packages: read

jobs:
  build:
    name: Build ESP32-S31 firmware
    uses: ./.github/workflows/build-firmware.yml
    with:
      version: ${{ github.sha }}
      container_image: ghcr.io/nyavana/ds5dongle-esp32s31-idf:master
